# Generated by Django 6.1.1 on 2026-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('face_embedding', models.JSONField(blank=True, default=list)),
                ('reference_photo_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
